/* BORRADO DE TABLAS */
/* BORRADO DE TIPOS */
/* SECUENCIAS */
/* CREACIÓN DE TIPOS */
/* CREACIÓN DE TABLAS */
/* CUERPOS DE TIPOS */

/* BORRADO DE TABLAS */
DROP TABLE BILLETES_TAB PURGE;
DROP TABLE FACTURAS_TAB;
DROP TABLE CLIENTES_TAB;
DROP TABLE CLASES_BILLETE_TAB;
DROP TABLE VUELOS_TAB;
DROP TABLE EMPLEADOS_TAB;
DROP TABLE AVIONES_TAB;


/* BORRADO DE TIPOS */
DROP TYPE FACTURA_OBJ FORCE;
DROP TYPE CLIENTE_OBJ FORCE;
DROP TYPE TARJETA_ARRAY FORCE;
DROP TYPE TARJETA_OBJ FORCE;
DROP TYPE BILLETE_LIST FORCE;
DROP TYPE BILLETE_OBJ FORCE;
DROP TYPE CLASE_BILLETE_OBJ FORCE;
DROP TYPE EQUIPAJE_OBJ FORCE;
DROP TYPE RECLAMACION_ARRAY FORCE;
DROP TYPE RECLAMACION_OBJ FORCE;
DROP TYPE VUELO_OBJ FORCE;
DROP TYPE INCIDENCIA_LIST FORCE;
DROP TYPE INCIDENCIA_OBJ FORCE;
DROP TYPE AVION_OBJ FORCE;
DROP TYPE EMPLEADO_LIST FORCE;
DROP TYPE EMPLEADO_OBJ FORCE;


/*SECUENCIAS*/
DROP SEQUENCE SFACTURAS;
DROP SEQUENCE SVUELOS;
DROP SEQUENCE SBILLETES;
DROP SEQUENCE SINCIDENCIAS;