/*SECUENCIAS*/
CREATE SEQUENCE SFACTURAS
START WITH 1
MAXVALUE 9999999999;

CREATE SEQUENCE SVUELOS
START WITH 1
MAXVALUE 9999999999;

CREATE SEQUENCE SBILLETES
START WITH 1
MAXVALUE 9999999999;

CREATE SEQUENCE SINCIDENCIAS
START WITH 1
MAXVALUE 9999999999;


/* CREACIÓN DE TIPOS */

CREATE OR REPLACE TYPE EMPLEADO_OBJ AS OBJECT(
	DNI        CHAR(9),
	NOMBRE     VARCHAR2(20),
	APELLIDOS  VARCHAR2(25),
	TLF        CHAR(13),
	EMAIL      VARCHAR2(30),
	DIRECCION  VARCHAR2(20),  
	CIUDAD     VARCHAR2(20),
	CP         CHAR(5),
	PAIS       VARCHAR2(15),
	CARGO      VARCHAR2(20),
	SALARIO    NUMBER(6,2),
	
	ORDER MEMBER FUNCTION OrdEmpleado(p_empleado IN EMPLEADO_OBJ) RETURN NUMBER
);
/
CREATE OR REPLACE TYPE EMPLEADO_LIST AS TABLE OF REF EMPLEADO_OBJ;
/
CREATE OR REPLACE TYPE AVION_OBJ AS OBJECT(
	MATRICULA	    CHAR(10),
	CAPACIDAD	    NUMBER(3,0),
	ULTIMA_REV	    DATE,		
	DISPONIBILIDAD	CHAR(2),
	
	ORDER MEMBER FUNCTION OrdAvion(p_avion IN AVION_OBJ) RETURN NUMBER
);
/
CREATE OR REPLACE TYPE INCIDENCIA_OBJ AS OBJECT(
	CODIGO       	CHAR(10),
	TIPO         	VARCHAR2(20),
	DESCRIPCION  	VARCHAR2(140),
	FECHA_CREACION	DATE,
	
	ORDER MEMBER FUNCTION OrdIncidencia(p_incidencia IN INCIDENCIA_OBJ) RETURN NUMBER
);
/
CREATE OR REPLACE TYPE INCIDENCIA_LIST AS TABLE OF INCIDENCIA_OBJ;
/
CREATE OR REPLACE TYPE VUELO_OBJ AS OBJECT(
	ID	            CHAR(10),
	ESTADO	        CHAR(2),
	ORIGEN	        CHAR(3),
	DESTINO        	CHAR(3),
	FECHA_SALIDA   	DATE,
	FECHA_LLEGADA  	DATE,
	PRECIO_BILLETES	NUMBER(6,2),
	AVION	        REF AVION_OBJ,
	ADMINISTRADOR	REF EMPLEADO_OBJ,
	PERSONAL		EMPLEADO_LIST,
	INCIDENCIAS		INCIDENCIA_LIST,
	
	CONSTRUCTOR FUNCTION VUELO_OBJ
		(SELF IN OUT NOCOPY VUELO_OBJ, estado CHAR, origen CHAR, destino CHAR, fecha_salida CHAR, fecha_llegada CHAR, precio_billetes NUMBER, matricula_avion CHAR, dni_administrador CHAR)
	RETURN SELF AS RESULT,
	
	ORDER MEMBER FUNCTION Ordvuelo(p_vuelo IN VUELO_OBJ) RETURN NUMBER,
	
	STATIC FUNCTION Asignar_empleado(dni_empleado CHAR, id_vuelo CHAR) RETURN NUMBER
);
/
CREATE OR REPLACE TYPE RECLAMACION_OBJ AS OBJECT(
	TIPO         	VARCHAR2(20),
	DESCRIPCION  	VARCHAR2(140),
	FECHA_CREACION	DATE,
	EMPLEADO     	REF EMPLEADO_OBJ,
	
	CONSTRUCTOR FUNCTION RECLAMACION_OBJ
		(SELF IN OUT NOCOPY RECLAMACION_OBJ, tipo CHAR, descripcion CHAR, fecha_creacion CHAR, dni_empleado CHAR)
	RETURN SELF AS RESULT,
	
	ORDER MEMBER FUNCTION OrdReclamacion(p_reclamacion IN RECLAMACION_OBJ) RETURN NUMBER
);
/
CREATE OR REPLACE TYPE RECLAMACION_ARRAY AS VARRAY(2) OF RECLAMACION_OBJ;
/
CREATE OR REPLACE TYPE EQUIPAJE_OBJ AS OBJECT(
	NUM_BULTOS		NUMBER(2,0),
	FRAGIL	    	CHAR(2),
	PESO_TOTAL		NUMBER(5,2),
	RECLAMACIONES	RECLAMACION_ARRAY
);
/
CREATE OR REPLACE TYPE CLASE_BILLETE_OBJ AS OBJECT(
	NOMBRE	      		VARCHAR2(20),
	VARIACION_PRECIO 	NUMBER(5,2),
	PESO_MAX     		NUMBER(2,0),
	IMPORTE_SUP  		NUMBER(3,2),
	
	ORDER MEMBER FUNCTION OrdClase(p_clase IN CLASE_BILLETE_OBJ) RETURN NUMBER
);
/
CREATE OR REPLACE TYPE BILLETE_OBJ AS OBJECT(
	ID       	CHAR(10),
	ASIENTO  	CHAR(3),
	PRECIO	 	NUMBER(5,2),
	ANULADO  	CHAR(2),
	IVA      	NUMBER(3,0),
	SUPLEMENTO	NUMBER(5,2),
	VUELO    	REF VUELO_OBJ,
	CLASE		REF CLASE_BILLETE_OBJ,
	EQUIPAJE	EQUIPAJE_OBJ,
	
	CONSTRUCTOR FUNCTION BILLETE_OBJ
		(SELF IN OUT NOCOPY BILLETE_OBJ, asiento CHAR, anulado CHAR, iva NUMBER, vuelo_id CHAR, clase_billete VARCHAR2, dni_cliente CHAR, num_factura CHAR)
	RETURN SELF AS RESULT,
	
	MAP MEMBER FUNCTION ReturnID RETURN NUMBER,
	
	STATIC FUNCTION Asignar_equipaje(id_billete CHAR, num_bultos NUMBER, fragil CHAR, peso_total NUMBER) RETURN NUMBER,
	STATIC FUNCTION Crear_reclamacion(id_billete CHAR, reclamacion RECLAMACION_OBJ) RETURN NUMBER,
	MEMBER PROCEDURE Recalcular_precio
);
/
CREATE OR REPLACE TYPE BILLETE_LIST AS TABLE OF REF BILLETE_OBJ;
/
CREATE OR REPLACE TYPE TARJETA_OBJ AS OBJECT (
	NUMERO			CHAR(16),
	TITULAR			VARCHAR2(45),
	FECHA_CADUCIDAD	DATE,
	CVV				CHAR(3),
	
	MAP MEMBER FUNCTION ReturnNumero RETURN NUMBER
);
/
CREATE OR REPLACE TYPE TARJETA_ARRAY AS VARRAY(3) OF TARJETA_OBJ;
/
CREATE OR REPLACE TYPE CLIENTE_OBJ AS OBJECT (
	DNI        	CHAR(9),
	PASAPORTE  	CHAR(10),
	NOMBRE     	VARCHAR2(20),
	APELLIDOS  	VARCHAR2(25),
	TLF        	CHAR(13),
	EMAIL      	VARCHAR2(30),
	DIRECCION  	VARCHAR2(20),  
	CIUDAD		VARCHAR2(20),
	CP			CHAR(5),
	PAIS		VARCHAR2(15),
	PASSWORD	VARCHAR2(20),
	TARJETAS	TARJETA_ARRAY,
	BILLETES	BILLETE_LIST,
	
	ORDER MEMBER FUNCTION OrdCliente(p_cliente IN CLIENTE_OBJ) RETURN NUMBER
);
/
CREATE OR REPLACE TYPE FACTURA_OBJ AS OBJECT (
	ID             	CHAR(10),
	IMPORTE_TOTAL  	NUMBER(7,2),
	FECHA_COMPRA   	DATE,
	CLIENTE        	REF CLIENTE_OBJ,
	TARJETA			CHAR(16),
	
	CONSTRUCTOR FUNCTION FACTURA_OBJ
		(SELF IN OUT NOCOPY FACTURA_OBJ, fecha_compra DATE, dni_cliente CHAR, num_tarjeta CHAR)
	RETURN SELF AS RESULT,
	
	ORDER MEMBER FUNCTION OrdFactura(p_factura IN FACTURA_OBJ) RETURN NUMBER
);
/
ALTER TYPE BILLETE_OBJ ADD ATTRIBUTE (CLIENTE REF CLIENTE_OBJ, FACTURA REF FACTURA_OBJ) CASCADE;