/* CREACIÓN DE TABLAS */
/
CREATE TABLE AVIONES_TAB OF AVION_OBJ(
	CONSTRAINT PK_MATRICULA_AVIONES 		PRIMARY KEY (MATRICULA),
	
	CONSTRAINT C_DISPONIBILIDAD_AVIONES		CHECK (DISPONIBILIDAD IN ('SI','NO')),
	
	CONSTRAINT NN_CAPACIDAD_AVIONES 		CAPACIDAD NOT NULL,
	CONSTRAINT NN_DISPONIBILIDAD_AVIONES 	DISPONIBILIDAD NOT NULL
);
/
CREATE TABLE EMPLEADOS_TAB OF EMPLEADO_OBJ(
	CONSTRAINT PK_DNI_EMPLEADOS 		PRIMARY KEY (DNI),

	CONSTRAINT C_CARGO_EMPLEADOS 		CHECK (CARGO IN ('ADMINISTRADOR','PILOTO','AZAFATA','TAQUILLA')),
	
	CONSTRAINT NN_NOMBRE_EMPLEADOS 		NOMBRE NOT NULL,
	CONSTRAINT NN_APELLIDOS_EMPLEADOS 	APELLIDOS NOT NULL,
	CONSTRAINT NN_EMAIL_EMPLEADOS 		EMAIL NOT NULL,
	CONSTRAINT NN_CARGO_EMPLEADOS 		CARGO NOT NULL,
	CONSTRAINT NN_SALARIO_EMPLEADOS 	SALARIO NOT NULL
);
/
CREATE TABLE VUELOS_TAB OF VUELO_OBJ(
	CONSTRAINT PK_ID_VUELOS					PRIMARY KEY (ID),
	
	CONSTRAINT C_ESTADO_VUELOS				CHECK (ESTADO IN ('D','EC','C','R','E')),
	CONSTRAINT C_PRECIO_BILLETES_VUELOS		CHECK (PRECIO_BILLETES >= 0),
	CONSTRAINT C_SALIDA_LLEGADA				CHECK (FECHA_SALIDA < FECHA_LLEGADA),
									
	CONSTRAINT NN_ESTADO_VUELOS 			ESTADO NOT NULL,
	CONSTRAINT NN_ORIGEN_VUELOS				ORIGEN NOT NULL,
	CONSTRAINT NN_DESTINO_VUELOS			DESTINO NOT NULL,
	CONSTRAINT NN_FECHA_SALIDA_VUELOS		FECHA_SALIDA NOT NULL,
	CONSTRAINT NN_FECHA_LLEGADA_VUELOS		FECHA_LLEGADA NOT NULL,
	CONSTRAINT NN_PRECIO_BILLETES_VUELOS	PRECIO_BILLETES NOT NULL,
	CONSTRAINT NN_AVION_VUELOS				CHECK (AVION IS NOT NULL),
	CONSTRAINT NN_ADMINISTRADOR_VUELOS		CHECK (ADMINISTRADOR IS NOT NULL),
	CONSTRAINT NN_PERSONAL_VUELOS			CHECK (PERSONAL IS NOT NULL),
											   
	AVION REFERENCES AVIONES_TAB,
	ADMINISTRADOR REFERENCES EMPLEADOS_TAB
)
NESTED TABLE PERSONAL STORE AS PERSONAL_NTAB,
NESTED TABLE INCIDENCIAS STORE AS INCIDENCIAS_NTAB(
	(CONSTRAINT PK_CODIGO_INCIDENCIAS    		PRIMARY KEY (CODIGO),
	
	CONSTRAINT C_TIPO_INCIDENCIAS       		CHECK (TIPO IN('R','AV','C')),

	CONSTRAINT NN_TIPO_INCIDENCIAS				TIPO NOT NULL,
	CONSTRAINT NN_DESCRIPCION_INCIDENCIAS		DESCRIPCION NOT NULL,
	CONSTRAINT NN_FECHA_CREACION_INCIDENCIAS	FECHA_CREACION NOT NULL)
);
ALTER TABLE PERSONAL_NTAB ADD(SCOPE FOR(COLUMN_VALUE) IS EMPLEADOS_TAB);
/
CREATE TABLE CLASES_BILLETE_TAB OF CLASE_BILLETE_OBJ(
	CONSTRAINT PK_NOMBRE_CLASESB			PRIMARY KEY (NOMBRE),
	
	CONSTRAINT C_VARIACION_PRECIO_CLASESB	CHECK (VARIACION_PRECIO >= 0),
	CONSTRAINT C_PESO_MAX_CLASESB    		CHECK (PESO_MAX >= 0 AND PESO_MAX <= 50),
	CONSTRAINT C_IMPORTE_SUP_CLASESB    	CHECK (IMPORTE_SUP >= 0),
	
	CONSTRAINT NN_VARIACION_PRECIO_CLASESB 	VARIACION_PRECIO NOT NULL,
	CONSTRAINT NN_PESO_MAX_CLASESB			PESO_MAX NOT NULL,
	CONSTRAINT NN_IMPORTE_SUP_CLASESB 		IMPORTE_SUP NOT NULL
);
/
CREATE TABLE CLIENTES_TAB OF CLIENTE_OBJ(
	CONSTRAINT PK_DNI_CLIENTES       	PRIMARY KEY (DNI),
	CONSTRAINT U_PASAPORTE_CLIENTES  	UNIQUE (PASAPORTE),
	
	CONSTRAINT NN_NOMBRE_CLIENTES 		NOMBRE NOT NULL,
	CONSTRAINT NN_APELLIDOS_CLIENTES 	APELLIDOS NOT NULL,
	CONSTRAINT NN_EMAIL_CLIENTES		EMAIL NOT NULL
)
NESTED TABLE BILLETES STORE AS BILLETES_NTAB;
/
CREATE TABLE FACTURAS_TAB OF FACTURA_OBJ(
	CONSTRAINT PK_ID_FACTURAS 				PRIMARY KEY (ID),
	
	CONSTRAINT C_IMPORTE_TOTAL_FACTURAS   	CHECK (IMPORTE_TOTAL >= 0),
	
	CONSTRAINT NN_IMPORTE_TOTAL_FACTURAS 	IMPORTE_TOTAL NOT NULL,
	CONSTRAINT NN_FECHA_COMPRA_FACTURAS		FECHA_COMPRA NOT NULL,
	CONSTRAINT NN_CLIENTE_FACTURAS			CHECK (CLIENTE IS NOT NULL),
	
	CLIENTE REFERENCES CLIENTES_TAB
);
/
CREATE TABLE BILLETES_TAB OF BILLETE_OBJ(
	CONSTRAINT PK_ID_BILLETES 			PRIMARY KEY (ID),
	
	CONSTRAINT C_PRECIO_BILLETES    	CHECK (PRECIO >= 0),
	CONSTRAINT C_ANULADO_BILLETES   	CHECK (ANULADO IN ('SI','NO')),
	CONSTRAINT C_IVA_BILLETES   		CHECK (IVA >= 0 AND IVA <= 100),
	CONSTRAINT C_SUPLEMENTO_BILLETES    CHECK (SUPLEMENTO >= 0),
	CONSTRAINT C_NUM_BULTOS_EQUIPAJE    CHECK (EQUIPAJE.NUM_BULTOS >= 1),
	CONSTRAINT C_FRAGIL_EQUIPAJE    	CHECK (EQUIPAJE.FRAGIL IN ('SI','NO')),
	CONSTRAINT C_PESO_TOTAL_EQUIPAJE    CHECK (EQUIPAJE.PESO_TOTAL > 0),
	
	CONSTRAINT NN_ASIENTO_BILLETES		ASIENTO NOT NULL,
	CONSTRAINT NN_PRECIO_BILLETES		PRECIO NOT NULL,
	CONSTRAINT NN_ANULADO_BILLETES 		ANULADO NOT NULL,
	CONSTRAINT NN_IVA_BILLETES 			IVA NOT NULL,
	CONSTRAINT NN_CLIENTE_BILLETES 		CHECK (CLIENTE IS NOT NULL),
	CONSTRAINT NN_FACTURA_BILLETES 		CHECK (FACTURA IS NOT NULL),
	CONSTRAINT NN_VUELO_BILLETES 		CHECK (VUELO IS NOT NULL),
	CONSTRAINT NN_CLASE_BILLETES 		CHECK (CLASE IS NOT NULL),
	
	/*CONSTRAINT NN_NUM_BULTOS_EQUIPAJE 	CHECK (EQUIPAJE.NUM_BULTOS IS NOT NULL),
	CONSTRAINT NN_FRAGIL_EQUIPAJE 		CHECK (EQUIPAJE.FRAGIL IS NOT NULL),
	CONSTRAINT NN_PESO_TOTAL_EQUIPAJE 	CHECK (EQUIPAJE.PESO_TOTAL IS NOT NULL),*/
	
	CLIENTE REFERENCES CLIENTES_TAB,
	FACTURA REFERENCES FACTURAS_TAB,
	VUELO REFERENCES VUELOS_TAB,
	CLASE REFERENCES CLASES_BILLETE_TAB
);
/
ALTER TABLE BILLETES_NTAB ADD(SCOPE FOR(COLUMN_VALUE) IS BILLETES_TAB);